# Generated by Django 2.1.7 on 2019-12-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='服务项目')),
            ],
            options={
                'verbose_name': '关于盖冠政务',
                'verbose_name_plural': '关于盖冠政务',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='盖冠政务')),
                ('info1', models.CharField(max_length=200, verbose_name='简介1')),
                ('info2', models.CharField(max_length=200, verbose_name='简介2')),
                ('img', models.ImageField(upload_to='imgs', verbose_name='背景图')),
                ('phone', models.CharField(max_length=100, verbose_name='联系电话')),
                ('address', models.CharField(max_length=200, verbose_name='联系地址')),
                ('web', models.CharField(max_length=200, verbose_name='政务官网')),
            ],
            options={
                'verbose_name': '盖冠政务',
                'verbose_name_plural': '盖冠政务',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('subject', models.CharField(max_length=100, verbose_name='主题')),
                ('msg', models.TextField(verbose_name='信息内容')),
            ],
            options={
                'verbose_name': '客户联系',
                'verbose_name_plural': '客户联系',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='服务群体')),
                ('img', models.ImageField(upload_to='imgs', verbose_name='图片')),
                ('info', models.CharField(max_length=50, verbose_name='服务内容')),
                ('url', models.URLField(verbose_name='链接')),
            ],
            options={
                'verbose_name': '服务群体',
                'verbose_name_plural': '服务群体',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('img', models.ImageField(upload_to='imgs', verbose_name='头像')),
                ('info', models.CharField(max_length=50, verbose_name='简介')),
                ('post', models.CharField(max_length=50, verbose_name='职位')),
            ],
            options={
                'verbose_name': '员工展示',
                'verbose_name_plural': '员工展示',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=50, verbose_name='服务内容')),
                ('item', models.CharField(choices=[('sta', '标准套餐'), ('upd', '升级套餐')], default='sta', max_length=5, verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '服务收费',
                'verbose_name_plural': '服务收费',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='服务项目')),
                ('info', models.CharField(max_length=50, verbose_name='简介')),
            ],
            options={
                'verbose_name': '主要服务',
                'verbose_name_plural': '主要服务',
            },
        ),
        migrations.CreateModel(
            name='Supers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=30, verbose_name='优势')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
            ],
            options={
                'verbose_name': '盖冠政务优势',
                'verbose_name_plural': '盖冠政务优势',
            },
        ),
    ]
