# Generated by Django 2.2.6 on 2019-12-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.BooleanField()),
                ('school', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('hobby', models.CharField(max_length=500)),
                ('strong_point', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('postal_code', models.IntegerField()),
                ('mail', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
