# Generated by Django 2.2.6 on 2019-12-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldform',
            name='sex',
            field=models.CharField(max_length=5),
        ),
    ]
