# Generated by Django 2.2.6 on 2019-12-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20191218_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fields', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
