# Generated by Django 2.2.6 on 2019-12-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20191219_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='name',
            new_name='title',
        ),
    ]
