# Generated by Django 2.2.6 on 2019-12-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='sex',
            field=models.CharField(max_length=50),
        ),
    ]
