# Generated by Django 2.2.6 on 2019-12-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20191221_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name_plural': '动态修改表单'},
        ),
        migrations.AlterModelOptions(
            name='fieldform',
            options={'verbose_name_plural': '表单对应的用户信息'},
        ),
        migrations.AlterField(
            model_name='field',
            name='address',
            field=models.BooleanField(default=False, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='field',
            name='age',
            field=models.BooleanField(default=False, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='field',
            name='city',
            field=models.BooleanField(default=False, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='field',
            name='date',
            field=models.BooleanField(default=False, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='field',
            name='hobby',
            field=models.BooleanField(default=False, verbose_name='爱好'),
        ),
        migrations.AlterField(
            model_name='field',
            name='is_used',
            field=models.BooleanField(default=True, verbose_name='是否启用本表单'),
        ),
        migrations.AlterField(
            model_name='field',
            name='mail',
            field=models.BooleanField(default=False, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.BooleanField(default=False, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='field',
            name='phone',
            field=models.BooleanField(default=False, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='field',
            name='postal_code',
            field=models.BooleanField(default=False, verbose_name='邮编'),
        ),
        migrations.AlterField(
            model_name='field',
            name='school',
            field=models.BooleanField(default=False, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='field',
            name='sex',
            field=models.BooleanField(default=False, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='field',
            name='strong_point',
            field=models.BooleanField(default=False, verbose_name='特长'),
        ),
        migrations.AlterField(
            model_name='field',
            name='text',
            field=models.BooleanField(default=False, verbose_name='普通文本'),
        ),
        migrations.AlterField(
            model_name='field',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='fieldform',
            name='address',
            field=models.CharField(max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='fieldform',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='fieldform',
            name='city',
            field=models.CharField(max_length=20, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='fieldform',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='fieldform',
            name='hobby',
            field=models.CharField(max_length=500, verbose_name='爱好'),
        ),
        migrations.AlterField(
            model_name='fieldform',
            name='mail',
            field=models.CharField(max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='fieldform',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='fieldform',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='fieldform',
            name='postal_code',
            field=models.IntegerField(verbose_name='邮编'),
        ),
        migrations.AlterField(
            model_name='fieldform',
            name='school',
            field=models.CharField(max_length=50, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='fieldform',
            name='sex',
            field=models.CharField(max_length=5, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='fieldform',
            name='strong_point',
            field=models.CharField(max_length=500, verbose_name='特长'),
        ),
        migrations.AlterField(
            model_name='fieldform',
            name='text',
            field=models.TextField(verbose_name='普通文本'),
        ),
    ]
