# Generated by Django 2.2.6 on 2019-12-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_auto_20191221_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FieldForm',
            new_name='UserInfo',
        ),
    ]
