# Generated by Django 2.2.6 on 2019-12-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_auto_20191221_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(max_length=20, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date',
            field=models.DateField(null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='hobby',
            field=models.CharField(max_length=500, null=True, verbose_name='爱好'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mail',
            field=models.CharField(max_length=50, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='postal_code',
            field=models.IntegerField(null=True, verbose_name='邮编'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='school',
            field=models.CharField(max_length=50, null=True, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(max_length=5, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='strong_point',
            field=models.CharField(max_length=500, null=True, verbose_name='特长'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='text',
            field=models.TextField(null=True, verbose_name='普通文本'),
        ),
    ]
